### ISSUE TITLE
Bluetooth issue 

### ISSUE THREAD

**Issue by konstantin-mohin** [zxcpoiu/react-native-incall-manager#87] opened 2018-05-14 01:59 UTC
Hi, I've tested the library a little bit, and I get different results for the same action, bluetooth headset is permanently connected to the phone, but only in the first time it works as expected.

4 attempts log
https://pastebin.com/R6RLKAyX

**Comment by zxcpoiu** [comment] 2018-05-15 06:44
On android, different OS has different Bluetooth control logics, some is buggy.

Originally, we use `setForceSpeakerPhone` `on / off / null`, to toggle audio route.
if set to null, it uses default route, for audio only call, the default route is `earpiece`, for video, the default route is speaker phone.

If a device use `default audio route` AND Bluetooth is connected, ideally, system OS would route audio to Bluetooth. But the behaviors are vary on different android version and manufacturers. iOS works fine in this approach.

So for Android, that's the main reason I add `choose audio route` support. To explicitly specify audio route works lot more better than system's behavior.

### You can get the idea below ( Android only ):

1. I listen and store audioDeviceState on redux somewhere in the state
2. we know exactly what audio route is currently using and we know current available audio devices
3. render your audio toggle button and display / highlight the current one according to `selectedAudioDevice`
4. when use press `toggle`, display a choose list according to `availableAudioDeviceList
5. anyway, use `InCallManager.chooseAudioRoute` after your app choose the preferred audio route.
6. update new list in the promise callback.

```
const {availableAudioDeviceList, selectedAudioDevice} = this.props.redux.audioDeviceState;
// ---- render according to selectedAudioDevice

........

// --- once user press / choose audio button, use this function to choose audio route

InCallManager.chooseAudioRoute(nextSelectedAvailableAudioDevice).then(newAudioDeviceList => {
    dispatch(newAudioDeviceList) // --- update your redux or state to render/update new audio button
});





```

**Comment by konstantin-mohin** [comment] 2018-06-10 10:13
I noticed that after a user receives a phone call and  `selectedAudioDevice ` was `BLUETOOTH` sound automatically goes to Earpeace.

Then I tried to manually forward the sound to a bluetooth device.

After calling the `chooseAudioRoute` and getting `selectedAudioDevice` = `BLUETOOTH` the sound was still directed to Earpeace.

**Comment by zxcpoiu** [comment] 2018-09-20 04:51
Yes, I've noticed the same on Note 4, but had forgot how I workaround it :smile:

**Comment by zxcpoiu** [comment] 2018-09-20 04:52
It seems fine recently, closing this for now, if it still has problem, please open new issue.

**Closed by zxcpoiu** 2018-09-20 04:52 UTC

**Comment by praneethwelideniya** [comment] 2022-01-27 18:39
Any Solution for this issue?

**Comment by gustavo-amaro** [comment] 2023-06-09 14:43
same here, any updates?

**Comment by katiahr** [comment] 2024-06-13 22:18
Any Solution for this issue?

**Comment by Bayramito** [comment] 2024-09-30 12:04
> On android, different OS has different Bluetooth control logics, some is buggy.
> 
> Originally, we use `setForceSpeakerPhone` `on / off / null`, to toggle audio route. if set to null, it uses default route, for audio only call, the default route is `earpiece`, for video, the default route is speaker phone.
> 
> If a device use `default audio route` AND Bluetooth is connected, ideally, system OS would route audio to Bluetooth. But the behaviors are vary on different android version and manufacturers. iOS works fine in this approach.
> 
> So for Android, that's the main reason I add `choose audio route` support. To explicitly specify audio route works lot more better than system's behavior.
> 
> ### You can get the idea below ( Android only ):
> 1. I listen and store audioDeviceState on redux somewhere in the state
> 2. we know exactly what audio route is currently using and we know current available audio devices
> 3. render your audio toggle button and display / highlight the current one according to `selectedAudioDevice`
> 4. when use press `toggle`, display a choose list according to `availableAudioDeviceList
> 5. anyway, use `InCallManager.chooseAudioRoute` after your app choose the preferred audio route.
> 6. update new list in the promise callback.
> 
> ```
> const {availableAudioDeviceList, selectedAudioDevice} = this.props.redux.audioDeviceState;
> // ---- render according to selectedAudioDevice
> 
> ........
> 
> // --- once user press / choose audio button, use this function to choose audio route
> 
> InCallManager.chooseAudioRoute(nextSelectedAvailableAudioDevice).then(newAudioDeviceList => {
>     dispatch(newAudioDeviceList) // --- update your redux or state to render/update new audio button
> });
> ```


It's so annoying in Android side we have this bug kind of behavior.  

The inCallManager api even does not gives you the device names that are connected via bluetooth. Yes there are some patches for that but since you can't use them,  nothing changes. 

In my case i have connected 2 bluetooth devices to the phone, 
1. bluetooth headphones
2. bluetooth speaker

The problem is`onAudioDeviceChanged` i get the names (with the patch) of the devices,  but even i tap one of them, routes me to EARPIECE but sound comes from random random device, and `selectedAudioDevice` is being EARPIECE.
Because of that,  i can't know which exact device is choosen so, i can render a tick in the list. 

Could not they do same api like in the callkeep ?
Which gives you a simple output like this 
` devices [{"name": "Speaker", "type": "Speaker"}, {"name": "Mi Portable Bluetooth Speaker", "type": "Bluetooth"}, {"name": "Phone", "selected": true, "type": "Phone"}]`

What i have done is, combined 2 repos, I grab the device list 
`RNCallKeep.getAudioRoutes().then(devices => {
        setRoutes(devices);
      });
`
Render them ... Then

`
    useEffect(() => {
      // listener for audio output changes

      if (Platform.OS === "ios") {
        RNCallKeep.addEventListener("didChangeAudioRoute", event => {
          // render ui based on selected for ios
        });
      }
      if (Platform.OS === "android") {
        InCallManager.start({media: "video"});
        DeviceEventEmitter.addListener("onAudioDeviceChanged", event => {
        // render ui based on selected for android
        });
      }
      return () => {
        RNCallKeep.removeEventListener("didChangeAudioRoute");
        DeviceEventEmitter.removeAllListeners("onAudioDeviceChanged");
      };
    }, []);
`

And for selection side,
`             if (Platform.OS === "ios") {
                      RNCallKeep.setAudioRoute(null, route.name);
                    } else {
                      InCallManager.chooseAudioRoute(convertDeviceNameToRouteAndroid(route.type));
                    }
`

BUT again, this is a very bad approach because since `chooseAudioRoute` requires type of the root, you can't select 1 or 2 bluetooth device if you have more than 1.
